### ISSUE TITLE
evilginx_parser

### ISSUE THREAD

**Issue by the-m00z** [kgretzky/evilginx#1]
python /root/tools/evilginx/evilginx_parser.py -i /var/log/evilginx-google.log -o /tmp/logs -c google.creds -x
[-] creds config corrupted.

**Comment by kgretzky** [comment]
You have to specify the full paths to google.creds file like so:
python /root/tools/evilginx/evilginx_parser.py -i /var/log/evilginx-google.log -o /tmp/logs -c /root/tools/evilginx/google.creds -x

I will make it more obvious in the update that file was not corrupted, but rather not found.
