### ISSUE TITLE
This script only supports Ubuntu/Debian

### ISSUE THREAD

**Issue by shivsah** [kgretzky/evilginx#10]
I'm using Kali Linux 2017.1 on VMWare and the distro is based on Debian...but it still gives this error running

>  **# ./install.sh**

**Comment by kgretzky** [comment]
Thanks for reporting. Will look into it. For now you can remove the lines
for install.sh script that check linux distro.

**Comment by shivsah** [comment]
Well instead of removing the complete conditions... I added kali on the if loop along with ubuntu and Debian... And it went straight to Populating apt-get cache...

________________________________

**Comment by kgretzky** [comment]
Perfect. Ill add same fix then.

**Comment by kgretzky** [comment]
Fixed in version 1.0.1.
