### ISSUE TITLE
live config

### ISSUE THREAD

**Issue by sepehrrahami** [kgretzky/evilginx#11]
hello, thank you for really helpful update. there is a problem with login.live.com. i tried many things but as you can see we have some problems in headers that proxy send to live.com.
this is what proxy sends:
`OPTIONS https://login.live.com/GetCredentialType.srf?vv=1600&mkt=EN-US&lc=1033 HTTP/1.1
Host: login.live.com
Connection: keep-alive
Access-Control-Request-Method: POST
Origin: http://login.fakelive.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Access-Control-Request-Headers: content-type, hpgact, hpgid
Accept: */*
Referer: http://login.fakelive.com/
Accept-Encoding: gzip, deflate, sdch, br
Accept-Language: en-US,en;q=0.8`
and this is what live.com send itself:
`POST https://login.live.com/GetCredentialType.srf?vv=1600&mkt=EN-US&lc=1033 HTTP/1.1
Host: login.live.com
Connection: keep-alive
Content-Length: 130
hpgid: 0
Accept: application/json
Origin: https://login.live.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
hpgact: 0
Content-type: application/json; charset=UTF-8
Referer: https://login.live.com/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.8
Cookie: uaid=***; MSPRequ=lt=***&co=1&id=N; MSPOK=***; CkTst=***`
{"username":"***@outlook.com","uaid":"***","isOtherIdpSupported":false,"checkPhones":true}

there is some problems like request send as a options not a post. also some headers and body are missing. do you have any idea?
thanks a lot

**Comment by kgretzky** [comment]
My guess is the `Origin` header is not modified in the request packet, because `login.live.com` is not proxied with additional Nginx site config. You may need to add a new site config just for proxying `login.live.com`.

**Comment by sepehrrahami** [comment]
thanks for reply. yes i test it, but same problem was remain.

**Comment by kgretzky** [comment]
Official `live.com` support will be added in next update. Closing for now.
