### ISSUE TITLE
new Google sign-in page

### ISSUE THREAD

**Issue by myfoxx** [kgretzky/evilginx#15]
The new Google sign-in page shows up on computers, phones, and tablets.
Now when you try login from evilginx still waiting for something ...
This morning still work, now .. no :/ 
I will check late if change  are required on nginx config, for example on the proxy_pass 

<img width="705" alt="screen shot 2017-05-02 at 14 49 40" src="https://cloud.githubusercontent.com/assets/4947022/25618295/b4457f82-2f46-11e7-8b92-fb7a56e2c105.png">

Thank's

**Comment by kgretzky** [comment]
Thanks for letting me know. Will be able to take a look in couple of days.

**Comment by kgretzky** [comment]
I've checked with Evilginx 1.0 and everything works as expected.
Are you using the updated version or the first public release from 3 weeks ago?

**Comment by myfoxx** [comment]
Thank's for the support. The version is the last, as u told me. 
Now works as expected. 
I have ricreate a new nginx profile.

Great job !!!
