### ISSUE TITLE
Compile error using latest OpenSSL

### ISSUE THREAD

**Issue by anirudhrata** [kgretzky/evilginx#2]
I get this error while compiling with the latest version of OpenSSL 

`src/event/ngx_event_openssl.c: In function ‘ngx_ssl_connection_error’:
src/event/ngx_event_openssl.c:2048:21: error: ‘SSL_R_NO_CIPHERS_PASSED’ undeclared (first use in this function)
             || n == SSL_R_NO_CIPHERS_PASSED                          /*  182 */
                     ^~~~~~~~~~~~~~~~~~~~~~~
src/event/ngx_event_openssl.c:2048:21: note: each undeclared identifier is reported only once for each function it appears in
objs/Makefile:1092: recipe for target 'objs/src/event/ngx_event_openssl.o' failed
make[2]: *** [objs/src/event/ngx_event_openssl.o] Error 1`

Version of OpenSSL:
Package: libssl-dev
Source: openssl
Version: 1.1.0e-1

Is there anyway I can compile using the older version which is supported?

**Comment by kgretzky** [comment]
Yes. I had similar issue with latest openssl being pushed to official repositories.
Usually installing this package will resolve the problem:
`apt-get install libssl1.0-dev`

This should install OpenSSL version 1.0.2 and the compilation will succeed. Don't forget to do `make clean` before you compile with new libssl.

**Comment by anirudhrata** [comment]
Thanks a lot, that worked.

**Comment by kgretzky** [comment]
Perfect! Closing issue.

**Comment by Benny1Blanco** [comment]
Index: src/event/ngx_event_openssl.c
===================================================================
--- src/event/ngx_event_openssl.c	(revision 7318)
+++ src/event/ngx_event_openssl.c	(revision 7319)
@@ -1194,4 +1194,8 @@
     } else {
         SSL_set_accept_state(sc->connection);
+
+#ifdef SSL_OP_NO_RENEGOTIATION
+        SSL_set_options(sc->connection, SSL_OP_NO_RENEGOTIATION);
+#endif
     }
