### ISSUE TITLE
Several errors.

### ISSUE THREAD

**Issue by linuxdaddy** [kgretzky/evilginx#22]
Hi bro, great job on this project. Sadly i am facing some problems, i get SSL verification errors, and when i create a link, the link, it says server not found. Here i got some screenshots of the errors, maybe you can help me. Keep the good job up!

![screenshot from 2017-05-24 22-52-05](https://cloud.githubusercontent.com/assets/26394383/26425186/3abb98c8-40d4-11e7-9258-e7861006c832.png)
![screenshot from 2017-05-24 22-52-47](https://cloud.githubusercontent.com/assets/26394383/26425187/3ac7c3f0-40d4-11e7-97ea-4532e578cf0c.png)
![screenshot from 2017-05-24 22-53-13](https://cloud.githubusercontent.com/assets/26394383/26425189/3acadebe-40d4-11e7-8251-0f9e474967db.png)
![screenshot from 2017-05-24 22-53-45](https://cloud.githubusercontent.com/assets/26394383/26425188/3ac94964-40d4-11e7-905c-24a057549c63.png)

**Comment by kgretzky** [comment]
Hi, thanks.

Domain `not-really-google.com` is just an example. You need to use your own registered domain.
