### ISSUE TITLE
Phishing link not working after setup enabled 

### ISSUE THREAD

**Issue by CyberTechnotrix** [kgretzky/evilginx#23]
![screen shot 2017-05-26 at 9 49 56 pm](https://cloud.githubusercontent.com/assets/26084755/26503175/5159d15a-425d-11e7-84b5-a89c8a99e181.png)
I get the message that this has been setup...but no link works ..resulting in no credential harvest

**Comment by CyberTechnotrix** [comment]
Is the phishing different from what i think ?

**Comment by kgretzky** [comment]
You need to provide more detailed information. I don't even know if you've set up everything correctly.
Refer to the blog post and do everything step by step.
