### ISSUE TITLE
Please consider adding "generic" OWA portal

### ISSUE THREAD

**Issue by jaredbarez** [kgretzky/evilginx#28]
![image](https://cloud.githubusercontent.com/assets/13761356/26724631/d3805950-479a-11e7-9cb6-3ce6ad63ecd4.png)
![image](https://cloud.githubusercontent.com/assets/13761356/26724652/eab83318-479a-11e7-8b8d-939ecc8b1050.png)
![image](https://cloud.githubusercontent.com/assets/13761356/26724661/f6ce31de-479a-11e7-9381-fb162b429376.png)

Thanks!

**Comment by kgretzky** [comment]
Will see! Thanks for suggestion.
