### ISSUE TITLE
nginx not getting started

### ISSUE THREAD

**Issue by p-naik** [kgretzky/evilginx#3]
[/etc/systemd/system/nginx.service:16] Missing

When trying to enable and start the nginx service , getting above error.

**Comment by kgretzky** [comment]
Is this the full error message? Can you paste the contents of nginx.service file?
Seems there is some error on line 16.

**Comment by p-naik** [comment]
[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

**Comment by kgretzky** [comment]
You need to remove EOF line. EOF was there only for the `cat` command to know when to stop writing to file and close it.

**Comment by p-naik** [comment]
got this error now

nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/evilginx-google.conf:24

nginx: [emerg] BIO_new_file("/etc/letsencrypt/live/notreallygoogle.com/fullchain.pem") failed (SSL: error:02001002:system library:fopen:No such file or directory:fopen('/etc/letsencrypt/live/notreallygoogle.com/fullchain.pem','r') error:2006D080:BIO routines:BIO_new_file:no such file)

nginx: configuration file /etc/nginx/nginx.conf test failed

**Comment by kgretzky** [comment]
Seems you haven't replaced the example domain with your own.
/etc/letsencrypt/live/notreallygoogle.com/ directory doesn't exist, which should store your LetsEncrypt SSL/TLS certificate.

**Comment by p-naik** [comment]
I'm not using SSL here.

**Comment by kgretzky** [comment]
You will then need to figure out how to change the config file yourself to suit your own setup.

**Comment by p-naik** [comment]
This is the complete error BTW: 

Apr 10 18:39:01 kali CRON[17623]: pam_unix(cron:session): session closed for user root
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16384) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16385) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16386) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16387) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16388) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16389) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16390) failed
Apr 10 18:43:12 kali kernel: FAT-fs (sdc): Directory bread(block 16391) failed
Apr 10 18:44:42 kali dbus-daemon[2063]: Activating service name='org.freedesktop.thumbnails.Cache1'
Apr 10 18:44:42 kali dbus-daemon[2063]: Successfully activated service 'org.freedesktop.thumbnails.Cache1'
Apr 10 18:44:51 kali systemd[1]: Starting The NGINX HTTP and reverse proxy server...
-- Subject: Unit nginx.service has begun start-up
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit nginx.service has begun starting up.
Apr 10 18:44:51 kali nginx[17734]: nginx: [warn] duplicate MIME type "text/html" in /etc/nginx/sites-enabled/evilginx-google.conf:24
Apr 10 18:44:51 kali nginx[17734]: nginx: the configuration file /etc/nginx/nginx.conf syntax is ok
Apr 10 18:44:51 kali nginx[17734]: nginx: [emerg] open() "/etc/nginx/nginx/logs/nginx.pid" failed (2: No such file or directory)
Apr 10 18:44:51 kali nginx[17734]: nginx: configuration file /etc/nginx/nginx.conf test failed
Apr 10 18:44:51 kali systemd[1]: nginx.service: Control process exited, code=exited status=1
Apr 10 18:44:51 kali systemd[1]: Failed to start The NGINX HTTP and reverse proxy server.
-- Subject: Unit nginx.service has failed
-- Defined-By: systemd
-- Support: https://www.debian.org/support
-- 
-- Unit nginx.service has failed.
-- 
-- The result is failed.
Apr 10 18:44:51 kali systemd[1]: nginx.service: Unit entered failed state.
Apr 10 18:44:51 kali systemd[1]: nginx.service: Failed with result 'exit-code'.

**Comment by kgretzky** [comment]
Go through the post again and this time register a domain for which you will be able to generate LetsEncrypt certificates. You are going to get errors if you do not follow the guide step by step.
