### ISSUE TITLE
Created URL not accessible after proper setup

### ISSUE THREAD

**Issue by savanapandit** [kgretzky/evilginx#30]
Cant hit the generated url after successful setup 

![capture1](https://user-images.githubusercontent.com/29270245/26914097-ab342d9e-4c38-11e7-9c82-d2954605b12b.PNG)

Now when i try to open the url , i get error site not accessible

Getting following errors for systemctl status nginx.service

![capture2](https://user-images.githubusercontent.com/29270245/26914356-2870ca0a-4c3a-11e7-9a73-be8b759d92fa.PNG)
 

Is there a way to debug this issue?

**Comment by kgretzky** [comment]
Hello!

It seems there is an issue in /etc/nginx/nginx.conf file. Can you post the contents of the file here, so that I can investigate?

**Comment by badazanambezi** [comment]
Hello!

I have the exact same issue. Here is nginx.conf file

#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    proxy_busy_buffers_size 256k;
    proxy_buffers 4 256k;
    proxy_buffer_size 128k;
    fastcgi_buffer_size 32k;
    fastcgi_buffers 16 16k;
    server_names_hash_bucket_size 128;
    include /etc/nginx/sites-enabled/*;
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on; 

#keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       80;
        server_name  localhost;

        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   html;
            index  index.html index.htm;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #    root           html;
        #    fastcgi_pass   127.0.0.1:9000;
        #    fastcgi_index  index.php;
        #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
        #    include        fastcgi_params;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
#    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}

}

**Comment by kgretzky** [comment]
Ahh ok, I didn't see the error in the screenshot. Look at the line when it says [emerg] and about file not found. You used domain not-really-google.com. You need to register your own domain and set it up to point to your server. What you did is just copy my example from the article.
