### ISSUE TITLE
Parsing problem

### ISSUE THREAD

**Issue by cibermanchego** [kgretzky/evilginx#31]
Hi there,
I'm usign your awesome tool to create a dropbox-like site. I setup the site and generate a URL, I navigate to the URL, logon, and get redirected(using Edge browser) to the site I specified(all cool so far).
When I try to parse the logs, I get this:

Parsing logs for site 'dropbox'...
[*] Debug mode on. Log was not truncated!
[+] Found creds:  0
[+] Found tokens: 0
In /var/log/ evilginx-dropbox.log is empty.
But if I go to /evilginx/logs/dropbox I can see the file created, 20170612_091301_0_tokens.txt, and the password is actually there.

Just tried with Facebook, with same results.

**Comment by poweroftrue** [comment]
When you setup evilginx, you can disable/enable auto parsing.

**Comment by cibermanchego** [comment]
OK, I see now. Did not understand how the parsing is supposed to work. Now I get it.
Thank you.

**Comment by poppydrayton** [comment]
I have same error. I can view the email i used for facebook login but there are no password and no session cookie. When i setup evilginx i have enabled auto parsing.
