### ISSUE TITLE
Credentials not Parsed

### ISSUE THREAD

**Issue by paragkamra** [kgretzky/evilginx#32]
Hi, i have successfully phished the user and i have got user credentials and session tokens but when i am trying it to parse it i am getting this error 
![2017-06-13 17_57_32-root ip-172-31-18-22_ _home_ubuntu_evilginx](https://user-images.githubusercontent.com/28391895/27082297-d73dc6b6-5061-11e7-8a4d-5b5f3675d521.png)
i have both credentials and session token file in Linkedin logs directory

**Comment by kgretzky** [comment]
Your logs may have already been auto-parsed. Check the /logs folder.
