### ISSUE TITLE
password reset

### ISSUE THREAD

**Issue by agendasep** [kgretzky/evilginx#34]
Hi, Do you look at google password reset ever? i configured the myaccount sub domain and the problem is when it verify password for second time you can't get back to your domain and will redirect to their website.
In other word can we see myaccount.google.com as myaccount.fake.com and it show our username and we see that we are login.
I want after authorize see the myaccount page that say i am login. (on the fake domain.)
Regards

**Comment by kgretzky** [comment]
That would require a lot of work to successfully proxy the whole website and make it functional.
You are free to try though.

**Comment by agendasep** [comment]
Hard work ;). Thank you
