### ISSUE TITLE
Error While Installing {parrot OS}

### ISSUE THREAD

**Issue by AnonyCracker** [kgretzky/evilginx#35]
when i want to install the script 
these Problem occur : 
This script only supports Ubuntu/Debian.
it doesnt support all Debian
👍

**Comment by poweroftrue** [comment]
Hello @AnonyCracker Evilginx only support Debian, what is your operating system?

Anyway you can help us in the experiment docker image here: https://github.com/kgretzky/evilginx/pull/45

You should able to run this on any operating system with Docker installed.
