### ISSUE TITLE
icloud-evilginx not working

### ISSUE THREAD

**Issue by SoniaKhan** [kgretzky/evilginx#36]
Here is screenshot

![screenshot_8](https://user-images.githubusercontent.com/27810053/28208621-4bc55a1e-68ac-11e7-8076-fee90f2e495e.png)

![screenshot_7](https://user-images.githubusercontent.com/27810053/28208639-59ac2f86-68ac-11e7-84ef-d6551488754e.png)

**Comment by ghost** [comment]
if you have solved the issue, please share your phishlet

**Comment by randalharris** [comment]
Contact me . randallharris129@gmail.com
