### ISSUE TITLE
hangs up at https://*********/signin/challenge/sl/password

### ISSUE THREAD

**Issue by Zalta79** [kgretzky/evilginx#4]
i've got everything up and running but when creds are entered in to site it does not redirect to the rc. 
the browser just keeps waiting for response from server

**Comment by kgretzky** [comment]
Hard for me to help with so little information. You will have to debug if this is nginx stalling the connection or a problem with web browser. Check out web developer tools in Chrome.

**Comment by Zalta79** [comment]
Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://accounts.google.com’) does not match the recipient window’s origin (‘https://my.site’).

**Comment by Zalta79** [comment]
I had a problem with my ssl cert on the accounts.my.site issue resolved

**Comment by kgretzky** [comment]
Great! Glad that worked out for you.

**Comment by sepehrrahami** [comment]
hi, sorry for opening this issue again.
i have same as that error and all of my certs are ok. the error is:

Failed to execute ‘postMessage’ on ‘DOMWindow’: The target origin provided (‘https://accounts.google.com’) does not match the recipient window’s origin (‘https://mysite.com’).

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://accounts.mysite.com/_/common/diagnostics/?hl=en&_reqid=37518&rt=j. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).
