### ISSUE TITLE
error when running evilginx.py

### ISSUE THREAD

**Issue by linuxdaddy** [kgretzky/evilginx#40]
Just installed evilginx and when i try to run it i get this error:

![screenshot from 2017-08-16 02-22-50](https://user-images.githubusercontent.com/26394383/29342234-f7e0ff6a-8229-11e7-8617-c72429952aa2.png)

I can tell that i am missing some files, can you help me fix this please?

**Comment by poweroftrue** [comment]
Hello @linuxdaddy, Evilginx only support Debian right now but you can help us in the experiment docker image here: https://github.com/kgretzky/evilginx/pull/45

You should able to run this on any operating system with Docker installed.
