### ISSUE TITLE
Getting evilginx working on Kali Linux 

### ISSUE THREAD

**Issue by vthaz** [kgretzky/evilginx#43]
Hi there, juz wanted to share my way of trying to install evilginx on Kali Linux. What have I overcome and with what I'am still having problems with.

Issues:
1. Lack of zlib library
solution: apt install zlib1g-dev
2. Location and then versions of the modules (prevents nginx from starting)
`
root@kali:~/evilginx#
 systemctl status nginx.service
● nginx.service - The NGINX HTTP and reverse proxy server
   Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sun 2017-10-15 12:31:22 EDT; 15s ago
  Process: 25771 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)

Oct 15 12:31:22 kali systemd[1]: Starting The NGINX HTTP and reverse proxy server...
Oct 15 12:31:22 kali nginx[25771]: nginx: [emerg] module "/etc/nginx/nginx/modules/ngx_http_auth_pam_module.so" version 1013005 instead of 1011002 in /etc/nginx/modules-enabled/50-mod-http-auth-pam.conf:1
Oct 15 12:31:22 kali nginx[25771]: nginx: configuration file /etc/nginx/nginx.conf test failed
Oct 15 12:31:22 kali systemd[1]: nginx.service: Control process exited, code=exited status=1
Oct 15 12:31:22 kali systemd[1]: Failed to start The NGINX HTTP and reverse proxy server.
Oct 15 12:31:22 kali systemd[1]: nginx.service: Unit entered failed state.
Oct 15 12:31:22 kali systemd[1]: nginx.service: Failed with result 'exit-code'.
`
solution: At first I just searched for missing modules and made symbolic links to where nginx was looking for them but as You can see that didn't solve the problem as after links were created modules version issue occured :/ Tried to check nginx.conf for any suggestions of module versions validation and how to disable it but failed. Any suggestions? (Sorry for mistakes, this is my first post)

**Comment by poweroftrue** [comment]
Hello @vthaz Evilginx only support Debian right now but you can help us in the experiment docker image here: https://github.com/kgretzky/evilginx/pull/45

You should able to run this on any operating system with Docker installed.

**Comment by acordeonmorado** [comment]
exactly the same problem.

**Comment by tokyoneon** [comment]
@vthaz
Did you find a working solution since creating this git issue?

@poweroftrue

Is there a non-docker solution for this `ngx_http_auth_pam_module.so` error?

`install.sh` error:

> 
>  \#\# Installing Evilginx daemon...
> 
> Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable nginx
> insserv: warning: current start runlevel(s) (empty) of script `nginx' overrides LSB defaults (2 3 4 5).
> insserv: warning: current stop runlevel(s) (0 1 2 3 4 5 6) of script `nginx' overrides LSB defaults (0 1 6).
> Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /etc/systemd/system/nginx.service.
> Job for nginx.service failed because the control process exited with error code.
> See "systemctl  status nginx.service" and "journalctl  -xe" for details.
> [-] Failed to start Nginx daemon.
> 

	> lsb_release -a
	No LSB modules are available.
	Distributor ID:	Kali
	Description:	Kali GNU/Linux Rolling
	Release:	kali-rolling
	Codename:	kali-rolling


	> apt-get update && apt-cache policy nginx
	nginx:
	  Installed: 1.13.6-2
	  Candidate: 1.13.6-2
	  Version table:
	 *** 1.13.6-2 500
		500 http://http.kali.org/kali kali-rolling/main amd64 Packages
		500 http://http.kali.org/kali kali-rolling/main i386 Packages
		100 /var/lib/dpkg/status


	> systemctl status nginx
	● nginx.service - The NGINX HTTP and reverse proxy server
	   Loaded: loaded (/etc/systemd/system/nginx.service; enabled; vendor preset: disabled)
	   Active: failed (Result: exit-code) since Fri 2017-12-08 13:51:49 EST; 7min ago
	  Process: 11879 ExecStartPre=/usr/sbin/nginx -t (code=exited, status=1/FAILURE)

	Dec 08 13:51:49 unknown systemd[1]: Starting The NGINX HTTP and reverse proxy server...
	Dec 08 13:51:49 unknown nginx[11879]: nginx: [emerg] dlopen() "/etc/nginx/nginx/modules/ngx_http_auth_pam_module.so" failed (/etc/nginx/nginx/modules/ngx_http_auth_pam_module.so: cannot op
	Dec 08 13:51:49 unknown nginx[11879]: nginx: configuration file /etc/nginx/nginx.conf test failed
	Dec 08 13:51:49 unknown systemd[1]: nginx.service: Control process exited, code=exited status=1
	Dec 08 13:51:49 unknown systemd[1]: nginx.service: Failed with result 'exit-code'.
	Dec 08 13:51:49 unknown systemd[1]: Failed to start The NGINX HTTP and reverse proxy server.

**Comment by tokyoneon** [comment]
@kgretzky

**Comment by kgretzky** [comment]
This is probably related to the fact that Kali comes with nginx preinstalled and the current configuration may interfere with the one already installed.

Please use clean Debian distro on external VPS as a remedy for that, for now.
