### ISSUE TITLE
Failed to start nginx daemon

### ISSUE THREAD

**Issue by acordeonmorado** [kgretzky/evilginx#46]
## Installing Evilginx daemon...

Synchronizing state of nginx.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable nginx
Job for nginx.service failed because the control process exited with error code.
See "systemctl  status nginx.service" and "journalctl  -xe" for details.
[-] Failed to start Nginx daemon.

Then I type 
nginx -t -c /etc/nginx/nginx.conf

root@loyal:~/Desktop/evilginx# nginx -t -c /etc/nginx/nginx.conf
nginx: [emerg] dlopen() "/etc/nginx/nginx/modules/ngx_http_auth_pam_module.so" failed (/etc/nginx/nginx/modules/ngx_http_auth_pam_module.so: cannot open shared object file: No such file or directory) in /etc/nginx/modules-enabled/50-mod-http-auth-pam.conf:1
nginx: configuration file /etc/nginx/nginx.conf test failed

any solution? thanks anyway

**Comment by Nekko21** [comment]
Replace the repository that you use on the kali repository and you will succeed. I do not advise you to use the repositories of parrot or another assembly there is all crooked

**Comment by acordeonmorado** [comment]
Solved! 

Really I have installed another kali distro (light), and it works. Thanks anyway.

**Comment by tokyoneon** [comment]
@Nekko21 

> "Replace the repository that you use on the kali repository and you will succeed. I do not advise you to use the repositories of parrot or another assembly there is all crooked"

Hey can you elaborate on your solution here.  Replace the repository with what?

> \> cat /etc/apt/sources.list
> deb http://http.kali.org/kali kali-rolling main non-free contrib
> \# deb-src http://http.kali.org/kali kali-rolling main non-free contrib

https://github.com/kgretzky/evilginx/issues/43

**Comment by tokyoneon** [comment]
@kgretzky

**Comment by cacaocaca** [comment]
@Nekko21 yes replace with what ? And you @acordeonmorado no have replace the reposity you have direct installed another distro lol

**Comment by kgretzky** [comment]
#43
