### ISSUE TITLE
please make sure that your domain name was 	   entered correctly

### ISSUE THREAD

**Issue by eubwxidc** [kgretzky/evilginx#49]
Having an issue generating the LetsEncrypt SSL cert. I'm sure my A Record is configured correctly.

	./evilginx.py setup --enable facebook -d my_website.com

	IMPORTANT NOTES:
	 - The following errors were reported by the server:

	   Domain: my_website.com
	   Type:   unauthorized
	   Detail: Invalid response from
	   http://my_website.com/.well-known/acme-challenge/IEf-BPDxSuxxxxxxxxxxxxxxxxxxxxx6gWIWrzrU
	   [xxx.xxx.xx.xxx]: 404

	   To fix these errors, please make sure that your domain name was
	   entered correctly and the DNS A/AAAA record(s) for that domain
	   contain(s) the right IP address.
	 - The following errors were reported by the server:

	   Domain: www.my_website.com
	   Type:   connection
	   Detail: Fetching
	   http://www.my_website.com/.well-known/acme-challenge/2dw-LgiFxxxxxxxxxxxxxxxxxxxxIYP-xnCrHw:
	   Error getting validation data

	   Domain: m.my_website.com
	   Type:   connection
	   Detail: DNS problem: NXDOMAIN looking up A for m.my_website.com

	   To fix these errors, please make sure that your domain name was
	   entered correctly and the DNS A/AAAA record(s) for that domain
	   contain(s) the right IP address. Additionally, please check that
	   your computer has a publicly routable IP address and that no
	   firewalls are preventing the server from communicating with the
	   client. If you're using the webroot plugin, you should also verify
	   that you are serving files from the webroot path you provided.
	[-] Failed to obtain certificates.
	[?] Do you want to auto-renew all obtained SSL/TLS certificates? [Y/n] n
	[*] Starting nginx daemon...

When cloning the evilginx repo, should I clone it to the `/var/www/` or `/etc/nginx/` directory?

**Comment by reda2882** [comment]
I'm having the same issue.

**Comment by kgretzky** [comment]
Please make sure to understand what domains are and how to properly register them, before posting issues.
