### ISSUE TITLE
RC / RT should not be readable for the victim

### ISSUE THREAD

**Issue by compr00t** [kgretzky/evilginx#5]
If you send out a link for phishing this link should consists of a domain and an ID at max:

`http://my-site.com/ServiceLogin?id=1234567890`

The RC and RT should be mapped in the backend to an uniq ID and not presented to the victim as this is minimizing the success rate drastically if you see an url like this:

`http://my-site.com/ServiceLogin?rc=http://my-real-site.com/login&rt=Session`

**Comment by kgretzky** [comment]
I agree.

It is an issue to implement though as parameters are handled via LuaJIT in nginx's  site config file. There is no way to access any database backend from there that I know of.

It would be enough to just base64 encode the parameters. If you can find out how to do it with LuaJIT, I would greatly appreciate it.

**Comment by kgretzky** [comment]
Fixed in version 1.0.0. Added base64 encoding for redirection parameters.
