### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by K555L** [kgretzky/evilginx#54]
Hello!
Thank you for the amazing tool you are sharing with the world for free, you are doing an amazing job!
The only problem is, there are no tutorials / guides at ALL on how to use the tool. If you do not have coding knowledge, it will be almost impossible to use. There is a short documentation on how to install it, but no documentation for example; TOR browser support, .onion sites support. How to configure it, how to build a new config, etc. Please take this in consideration, a lot of people cannot really use it because of leak of knowledge.

Thank you.

**Comment by kgretzky** [comment]
Thanks!

I will check with the documentation department to see if there is still anyone working there.
Feel free to contribute if you want.

**Comment by K555L** [comment]
I will be more then happy to contribute, write down tutorials, video tutorials, but I first need to personally know how to use it / create configs for any website, make it work under TOR .onion domains, etc.

**Comment by K555L** [comment]
Any update ?

**Comment by kgretzky** [comment]
It is opensource. Study code and find out - this is the main point of why we are here.

**Comment by jeretc** [comment]
If anyone needs an infograph tutorial..

https://github.com/jeretc/evilginx2-infograph
