### ISSUE TITLE
syntax error near unexpected token

### ISSUE THREAD

**Issue by jhonathanmarucs** [kgretzky/evilginx#6]
i fallow all the necessary steps but at the point when i tray to enable nginx i get this  -

systemctl enable nginx
#    Loaded: error (Reason: Bad message)
-bash: syntax error near unexpected token `('
root@googlegoogIe:~# systemctl enable nginx
Failed to execute operation: Bad message

systemctl start nginx
Failed to start nginx.service: Unit nginx.service failed to load: Bad message. See system logs and 'systemctl status nginx.service' for details.

# systemctl status nginx.service
● nginx.service - The NGINX HTTP and reverse proxy server
   Loaded: error (Reason: Bad message)
   Active: inactive (dead)

How to fid thix?

**Comment by kgretzky** [comment]
Can you paste the contents of your `/etc/systemd/system/nginx.service` file?

**Comment by jhonathanmarucs** [comment]
Thank you for your answer.

( /etc/systemd/system/nginx.service ) =

cat <<EOF > /etc/systemd/system/nginx.service
[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF

**Comment by kgretzky** [comment]
Make sure these are the only contents of the file:
```
[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

[Install]
WantedBy=multi-user.target
```
The rest are Linux commands to create that file.

**Comment by jhonathanmarucs** [comment]
Still not work
Now /etc/systemd/system/nginx.service =

[Unit]
Description=The NGINX HTTP and reverse proxy server
After=syslog.target network.target remote-fs.target nss-lookup.target

[Service]
Type=forking
PIDFile=/run/nginx.pid
ExecStartPre=/usr/sbin/nginx -t
ExecStart=/usr/sbin/nginx
ExecReload=/bin/kill -s HUP $MAINPID
ExecStop=/bin/kill -s QUIT $MAINPID
PrivateTmp=true

Still not working

[Install]
WantedBy=multi-user.target

~# systemctl enable nginx Created symlink from /etc/systemd/system/multi-user.target.wants/nginx.service to /etc/systemd/system/nginx.service.

~#systemctl start nginx
Job for nginx.service failed. See 'systemctl status nginx.service' and 'journalctl -xn' for details.

**Comment by kgretzky** [comment]
Still same error? You need to check if nginx was properly installed and retrace all steps. Try to figure out why it must be failing. I can't help without additional information.

**Comment by jhonathanmarucs** [comment]
Thank you for your help,i will tray to find the problem and i will post ir here once is fixet.
