### ISSUE TITLE
Google: Not working on Mobile

### ISSUE THREAD

**Issue by DarkParticle** [kgretzky/evilginx#8]
On My PC it works seamlessly, but on my iphone, it is in a loading loop after entering the Username and hitting Next.

**Comment by kgretzky** [comment]
Is it for the Google site? New sign-in page or the old one?

**Comment by DarkParticle** [comment]
The New one

**Comment by kgretzky** [comment]
Only on iPhone? Have you checked Android phone maybe?

**Comment by DarkParticle** [comment]
i just tried it on an android device and it is working. So i just used my iphone again and Voila.... Its working now. Maybe some DNS issues or something was there before. All Good now.

**Comment by kgretzky** [comment]
Ok, thats good to know. Thanks! Closing.
