### ISSUE TITLE
Google phishing detection

### ISSUE THREAD

**Issue by timwr** [kgretzky/evilginx#9]
Hi @kgretzky 
Great project!
Quick question: Won't this trigger Google chromes phishing detection if opened with Chrome (with usage statistics, etc, enabled)?

**Comment by kgretzky** [comment]
Hi Tim.
Thanks! In my testing, it triggered SafeBrowsing protection once, but all I
had to do was modify the URL slightly and alert was gone.
I've released it to the public for others to check Evilginx detectability
as well.
